export interface Video {
    id: number,
    objectId: string,
    tittle: string,
    uploadDate: Date,
    duration: number,
    channelSettingsId: number,
    channelName: string,
    channelNikName: string,
    channel_URL: string,
    channelProfilePhoto: string,
    channelBanner: string,
    videoUrl: string,
    vRoomVideoUrl: string,
    description: string,
    channelSubscriptionCount: number,
    viewCount: number,
    likeCount: number,
    dislikeCount: number,
    commentCount: number,
    isShort: boolean,
    cover: string,
    visibility: boolean,
    isAgeRestriction: boolean,
    isCopyright: boolean,
    audience: string,
};